QDRANT_HOST = "localhost"
QDRANT_PORT = 6333

PATENT_DIRECTORY = "television"

CHUNKS_COLLECTION_NAME = "patent_chunks"
PATENTS_COLLECTION_NAME = "patents"

EMBEDDING_MODEL = "Qwen/Qwen3-Embedding-0.6B"
VECTOR_SIZE = 1024

USE_REMOTE_LLM = True
QUERY_LLM_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
QUERY_LLM_REMOTE_BASE_URL = "http://192.168.2.213:8000/v1"
QUERY_LLM_REMOTE_MODEL = "nvidia/Qwen3.6-35B-A3B-NVFP4"
QUERY_LLM_REMOTE_API_KEY = "EMPTY"

USE_REMOTE_RERANKER = True
LOCAL_RERANKER_MODEL = "BAAI/bge-reranker-v2-m3"
RERANKER_REMOTE_BASE_URL = "http://192.168.2.213:8001"
RERANKER_REMOTE_MODEL = "BAAI/bge-reranker-v2-m3"
RERANKER_REMOTE_API_KEY = "EMPTY"
RERANKER_REQUEST_TIMEOUT = 360.0

MAX_CHUNK_TOKENS = 512
MIN_CHUNK_TOKENS = 20
MIN_CHUNK_WORDS = 8

# Number of chunks to upload to Qdrant in one request
BATCH_SIZE = 100

MAX_HEADING_LENGTH = 100
MAX_HEADING_WORDS = 12
ALLCAPS_MIN_ALPHA = 3

VALIDATOR_NORMALIZE_WHITESPACE = True
VALIDATOR_REJECT_HEADING_ONLY = True
VALIDATOR_REJECT_LOW_INFO = True
VALIDATOR_LOW_INFO_THRESHOLD = 0.3
VALIDATOR_REJECT_DEGENERATE_OVERLAP = True
VALIDATOR_DEGENERATE_OVERLAP_THRESHOLD = 0.9
VALIDATOR_HEADING_ONLY_MAX_WORDS = 3

DEBUG_CHUNKS = False
DEBUG_CHUNKS_DIR = "debug_chunks"

TOKEN_COUNT_CACHE_SIZE = 4096

PATENT_VIEW_URL_TEMPLATE = "https://www.qubeip.com/en/patent-view/{patent_id}"

STREAMLIT_PAGE_TITLE = "Patent Semantic Search"
STREAMLIT_LAYOUT = "wide"
HISTORY_DB_PATH = "data/search_history.db"

PATENT_CANDIDATE_TOP_K = 300
CANDIDATE_CHUNKS_PER_PATENT = 3
FINAL_TOP_K = 10
MIN_SEMANTIC_WEIGHT = 0.55
MAX_SECONDARY_WEIGHT = 0.20
MAX_WEAK_SIGNAL_WEIGHT = 0.10
SEM_STRUCT_SPLIT_RATIO = 0.7
EXCLUSION_PENALTY_WEIGHT = 0.5
EXCLUSION_HARD_FILTER_THRESHOLD = None
STRUCTURE_COVERAGE_MIN_MULTIPLIER = 0.7
RERANK_FINE_STAGE_TOP_N = 40
MAX_RELATIONSHIPS_SCORED = 5
MAX_OPTIMIZATION_TARGETS_SCORED = 5
MAX_EXCLUSIONS_SCORED = 5
REQUIRED_IMPORTANCE_BOOST = 0.2
STRUCTURED_SIGNAL_MIN_IMPORTANCE = 0.5